#普通一个变量名前缀
url:  https://192.168.5.160

#使用两个遍历名前缀
server:
   host: https://192.168.5.160


#一个变量名数组表示方法：

servers:
      -192.168.5.160
      -192.168.5.161
      -192.168.5.162

#多个变量名表示方法
srs:
  host:
    -192.168.5.160
    -192.168.5.161
    -192.168.5.162


#spring profile 使用例子

se :
  address: 192.165.5.160
---
spring:
  profiles: dev
  server:
      address: 127.0.0.1
---
spring:
  profiles: test
  server:
    address: 192.168.5.160

#表示上面的profile 会根据选择动态的调整使用哪个配置


